name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PASSWORD }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.SSH_HOST }}
          EC2_USER: ${{ secrets.SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/awsdeploy
            git pull origin dev
            # Add any additional commands to build, test, or restart your application
          EOF
